[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"

[zh]
  languageName = "Mandarin"
  contentDir = "content/zh"
  weight = 20
  [zh.params]
    languageISO = "ZH"
