# Meta Data for SEO

## Homepage
title = "Lotus Docs"
titleSeparator = "-"
titleAddition = "Home"
description = "Documentation for Lotus - the reference node implementation for the Filecoin network."

## Open Graph
images = ["lotus.png"]
ogLocale = "en_US"
domainTLD = "lotus.filecoin.io"
titleHome = "Lotus Docs"

## Twitter Cards
twitterSite = "@filecoin"
twitterCreator = "@_FilOz"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Lotus"
schemaAuthor = "FilOz"
schemaAuthorTwitter = "https://x.com/_FilOz"
schemaAuthorLinkedIn = "https://www.linkedin.com/company/filoz/"
schemaAuthorGitHub = "https://github.com/filecoin-project"
schemaLocale = "en-US"
schemaLogo = "lotus.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "lotus.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/filecoin"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/filecoin-project/lotus-docs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Developed and Maintained by FilOz."
footer_link = "https://filoz.org"

# Feed
copyRight = ""

# Alert
alert = false
alertDismissable = true
alertText = ""

# Edit Page
docsRepo = "https://github.com/filecoin-project/lotus-docs"
docsRepoBranch = "main"
editPage = true
repoHost = "GitHub"

[options]
    lazySizes = true
    clipBoard = true
    instantPage = false
    flexSearch = true
    darkMode = true
    bootStrapJs = true
    breadCrumb = false 
    highLight = true
    kaTex = false
    progressBar = true
    collapsibleSidebar = true
    multilingualMode = true
    docsVersioning = false # Not yet functional
