name: Upload site to Filecoin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  upload:
    env:
      GITHUB_TOKEN: ${{ secrets.FILECOIN_PIN_GH_TOKEN }}
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload to Filecoin
        uses: filecoin-project/filecoin-pin/.github/actions/filecoin-pin-upload-action@caf15149d621b6675fb4e35975d08ce830dfc4ff
        with:
          privateKey: ${{ secrets.FILECOIN_WALLET_KEY }}
          path: public
          minDays: 30
          maxTopUp: ${{ github.event_name == 'pull_request' && '0.0001' || '0.01' }}
          providerAddress: "0xa3971A7234a3379A1813d9867B531e7EeB20ae07"
