name: Upload to Filecoin

on:
  workflow_run:
    workflows: ["Build Site"]
    types: [completed]
  workflow_dispatch:  # Allow manual triggers
    inputs:
      artifact_name:
        description: 'Artifact name (for manual testing only, e.g., filecoin-build-pr-822)'
        required: false
        type: string

permissions:
  contents: read
  actions: read        # needed to download artifacts
  pull-requests: write # needed to comment on PRs

jobs:
  upload:
    # Only upload if build succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.FILECOIN_PIN_GH_TOKEN }}
    steps:
      - name: Upload to Filecoin
        uses: sgtpooki/filecoin-upload-action@main
        with:
          mode: upload
          artifact_name: ${{ inputs.artifact_name }} # only used if manually input from the action trigger UI
          walletPrivateKey: ${{ secrets.FILECOIN_WALLET_KEY }}
          minDays: "30"
          # 0.0001 USDFC for PRs, 0.10 USDFC for main
          maxTopUp: ${{ github.event.workflow_run.event == 'pull_request' && '0.0001' || '0.01' }}
          providerAddress: "0xa3971A7234a3379A1813d9867B531e7EeB20ae07"
